name: CI infra

on:
  push:
    paths:
      - 'infra/**'
      - '.github/workflows/ci-infra.yml'
  pull_request:
    paths:
      - 'infra/**'
      - '.github/workflows/ci-infra.yml'

permissions:
  contents: read

jobs:
  bicep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Bicep
        run: az bicep install

      - name: Build
        run: az bicep build --file infra/main.bicep --stdout > /dev/null

      - name: Build parameters
        run: az bicep build-params --file infra/main.bicepparam --stdout > /dev/null

      - name: Lint
        run: az bicep lint --file infra/main.bicep
